#! /bin/bash

usage_exit() {
        echo "Usage: $0 [-n] [-h] [-o ] setting.txt" 1>&2
        exit 1
}

OUTPUT_FILENAME=out
while getopts no:h OPT
do
    case $OPT in
        p) ONLY_PSN_FLAG=true
            ;;
        e) ONLY_ESN_FLAG=true
            ;;
        o)  OUTPUT_FILENAME=$OPTARG
            ;;
        h)  usage_exit
            ;;
        \?) usage_exit
            ;;
    esac
done
shift $((OPTIND - 1))

SCRIPT=$0
if [ -n "`readlink $SCRIPT`" ] ; then
    SCRIPT="`readlink $SCRIPT`"
fi
SRC_DIR=$(cd $(dirname $SCRIPT) && pwd)/src
NS2_SCRIPT=espsn.tcl
ESPSN_SCRIPT=espsn_interface.py
SETTING_FILE=$(cd $(dirname $1) && pwd)/$(basename $1)
WORKING_DIR=`dirname $SETTING_FILE`

cd $SRC_DIR
if [ ! $ONLY_ESN_FLAG ] ; then
    NS2_CMD="ns ${NS2_SCRIPT} ${SETTING_FILE} ${WORKING_DIR}/${OUTPUT_FILENAME}"
    eval $NS2_CMD
fi

if [ ! $ONLY_PSN_FLAT ] ; then
    ESPSN_CMD="python ${ESPSN_SCRIPT} ${SETTING_FILE} ${WORKING_DIR}/${OUTPUT_FILENAME}.tcp ${WORKING_DIR}/${OUTPUT_FILENAME}"
    eval $ESPSN_CMD
fi

