#! /bin/bash

SCRIPT=$0
if [ -n "`readlink $SCRIPT`" ] ; then
    SCRIPT="`readlink $SCRIPT`"
fi
SRC_DIR=$(cd $(dirname $SCRIPT) && pwd)/src
GENERATE_SETTING=${SRC_DIR}/generate_setting.py
python $GENERATE_SETTING $@
